
import java.util.ArrayList;
import javax.management.Query;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class CarArchive extends javax.swing.JDialog {
    DefaultTableModel model;
    Operations op = new Operations();

    /**
     * Creates new form CarArchive
     */
    public CarArchive(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) car_tabel.getModel();
        CarView();
        carNumber();
    }

        public void carNumber(){
            count_label.setText("0");
            int i = op.carCount();
            String ii = String.valueOf(i);
            count_label.setText(ii);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sherry_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        year_field = new javax.swing.JTextField();
        brand_field = new javax.swing.JTextField();
        model_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        color_field = new javax.swing.JTextField();
        gear_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fuel_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        km_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        casetype_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        motorpower_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        price_field = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        car_tabel = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        adad = new javax.swing.JPanel();
        count_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        message3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        message2.setBackground(new java.awt.Color(255, 51, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Car Sherry :");

        sherry_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sherry_fieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Car Model :");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Car Fuel:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Car Brand :");

        year_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_fieldActionPerformed(evt);
            }
        });

        brand_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_fieldActionPerformed(evt);
            }
        });

        model_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_fieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Car Year :");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Car Gear :");

        color_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_fieldActionPerformed(evt);
            }
        });

        gear_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gear_fieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Car Case Type :");

        fuel_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuel_fieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Car Km :");

        km_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                km_fieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Car Name Motor Power :");

        casetype_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casetype_fieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Car Color :");

        motorpower_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorpower_fieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setText("Car Price :");

        price_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_fieldActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(255, 255, 255));
        add_btn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 51, 0));
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(add_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(color_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(motorpower_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casetype_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(km_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gear_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fuel_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(year_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(model_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sherry_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brand_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(brand_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sherry_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuel_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gear_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(km_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casetype_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(motorpower_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(color_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_btn)
                .addGap(15, 15, 15))
        );

        car_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "car_brand", "car_sherry", "car_model", "car_year", "car_fuel", "car_gear", "car_km", "car_caseType", "car_motorPower", "car_color", "car_price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        car_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(car_tabel);
        if (car_tabel.getColumnModel().getColumnCount() > 0) {
            car_tabel.getColumnModel().getColumn(0).setResizable(false);
            car_tabel.getColumnModel().getColumn(1).setResizable(false);
            car_tabel.getColumnModel().getColumn(2).setResizable(false);
            car_tabel.getColumnModel().getColumn(3).setResizable(false);
            car_tabel.getColumnModel().getColumn(4).setResizable(false);
            car_tabel.getColumnModel().getColumn(5).setResizable(false);
            car_tabel.getColumnModel().getColumn(6).setResizable(false);
            car_tabel.getColumnModel().getColumn(7).setResizable(false);
            car_tabel.getColumnModel().getColumn(8).setResizable(false);
            car_tabel.getColumnModel().getColumn(9).setResizable(false);
            car_tabel.getColumnModel().getColumn(10).setResizable(false);
            car_tabel.getColumnModel().getColumn(11).setResizable(false);
        }

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_fieldKeyReleased(evt);
            }
        });

        adad.setBackground(new java.awt.Color(255, 255, 255));

        count_label.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        count_label.setForeground(new java.awt.Color(204, 204, 204));
        count_label.setText("5");

        javax.swing.GroupLayout adadLayout = new javax.swing.GroupLayout(adad);
        adad.setLayout(adadLayout);
        adadLayout.setHorizontalGroup(
            adadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adadLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        adadLayout.setVerticalGroup(
            adadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adadLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(count_label)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 27)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("My Car Archive Management System");

        message1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        message1.setForeground(new java.awt.Color(0, 153, 51));

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 204));

        message3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        message3.setForeground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout message2Layout = new javax.swing.GroupLayout(message2);
        message2.setLayout(message2Layout);
        message2Layout.setHorizontalGroup(
            message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, message2Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(message2Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(adad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(message2Layout.createSequentialGroup()
                                .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        message2Layout.setVerticalGroup(
            message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(message2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(message2Layout.createSequentialGroup()
                        .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(message2Layout.createSequentialGroup()
                                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(message2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(message1))
                            .addComponent(message3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(message2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(message2Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(message2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(message2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyReleased
        String query = search_field.getText();
        filter(query);
    }//GEN-LAST:event_search_fieldKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String brand = brand_field.getText();
        String sherry = sherry_field.getText();
        String modelll = model_field.getText();
        String year = year_field.getText();
        String fuel = fuel_field.getText();
        String gear = gear_field.getText();
        String km = km_field.getText();
        String casetype = casetype_field.getText();
        String motorpower = motorpower_field.getText();
        String color = color_field.getText();
        String price = price_field.getText();

        int selectedrow = car_tabel.getSelectedRow();

        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                    message3.setText("Car table null!");
            }
            else{
                message3.setText("Car selected update!");
            }
        }
        
        else{
            int id = (int)model.getValueAt(selectedrow,0);
            op.carUpdate(id,brand, sherry, modelll, year, fuel, gear, km, casetype, motorpower, color, price);
            CarView();
            message1.setText("Car update succesfull");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        message1.setText("");
        int selectedRow = car_tabel.getSelectedRow();

        if (selectedRow == -1){
            if(model.getRowCount() == 0){
                message1.setText("Car table null");
            }
            else{
                message1.setText("Car select delete");
            }
        }
        else{
            int id =(int)model.getValueAt(selectedRow,0);
            op.carDelete(id);
            CarView();
            message1.setText("Car delete succesfull");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void car_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car_tabelMouseClicked
        int selectedrow = car_tabel.getSelectedRow();

        brand_field.setText(model.getValueAt(selectedrow,1).toString());
        sherry_field.setText(model.getValueAt(selectedrow,2).toString());
        model_field.setText(model.getValueAt(selectedrow,3).toString());
        year_field.setText(model.getValueAt(selectedrow,4).toString());
        fuel_field.setText(model.getValueAt(selectedrow,5).toString());
        gear_field.setText(model.getValueAt(selectedrow,6).toString());
        km_field.setText(model.getValueAt(selectedrow,7).toString());
        casetype_field.setText(model.getValueAt(selectedrow,8).toString());
        motorpower_field.setText(model.getValueAt(selectedrow,9).toString());
        color_field.setText(model.getValueAt(selectedrow,10).toString());
        price_field.setText(model.getValueAt(selectedrow,11).toString());
    }//GEN-LAST:event_car_tabelMouseClicked

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        message1.setText("");

        String brand = brand_field.getText();
        String sherry = sherry_field.getText();
        String modelll = model_field.getText();
        String year = year_field.getText();
        String fuel = fuel_field.getText();
        String gear = gear_field.getText();
        String km = km_field.getText();
        String casetype = casetype_field.getText();
        String motorpower = motorpower_field.getText();
        String color = color_field.getText();
        String price = price_field.getText();
        op.carAdd(brand,sherry,year,modelll,fuel,gear,km,casetype,motorpower,color,price);
        CarView();
        message1.setText("Basarıyla Eklendi.");
    }//GEN-LAST:event_add_btnActionPerformed

    private void price_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_fieldActionPerformed

    private void motorpower_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorpower_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorpower_fieldActionPerformed

    private void casetype_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casetype_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casetype_fieldActionPerformed

    private void km_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_km_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_km_fieldActionPerformed

    private void fuel_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuel_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuel_fieldActionPerformed

    private void gear_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gear_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gear_fieldActionPerformed

    private void color_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color_fieldActionPerformed

    private void model_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_fieldActionPerformed

    private void brand_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_fieldActionPerformed

    private void year_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_fieldActionPerformed

    private void sherry_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sherry_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sherry_fieldActionPerformed
    public void filter(String query){
        
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(model);
        car_tabel.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(query));
        
    }
    
    
        public void CarView(){
            model.setRowCount(0);
            ArrayList<Car> cars = new ArrayList<Car>();
            cars = op.CarCome();
            
            if(cars != null){
                for(Car carx : cars){
                   Object[] add = {
                      carx.getId(),carx.getCar_brand(),carx.getCar_sherry(),carx.getCar_model(),carx.getCar_year(),carx.getCar_fuel(),carx.getCar_gear(),carx.getCar_km(),carx.getCar_caseType(),carx.getCar_motorPower(),carx.getCar_color(),carx.getCar_price()
                   };
             model.addRow(add);
             }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarArchive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarArchive dialog = new CarArchive(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adad;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField brand_field;
    private javax.swing.JTable car_tabel;
    private javax.swing.JTextField casetype_field;
    private javax.swing.JTextField color_field;
    private javax.swing.JLabel count_label;
    private javax.swing.JTextField fuel_field;
    private javax.swing.JTextField gear_field;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField km_field;
    private javax.swing.JLabel message1;
    private javax.swing.JPanel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JTextField model_field;
    private javax.swing.JTextField motorpower_field;
    private javax.swing.JTextField price_field;
    private javax.swing.JTextField search_field;
    private javax.swing.JTextField sherry_field;
    private javax.swing.JTextField year_field;
    // End of variables declaration//GEN-END:variables
}
